### ISSUE TITLE
IT8951 and beaglebone

### ISSUE THREAD

**Issue by MaBecker** [petrkr/it8951usb#1]
build it8951 works on beaglebone black without issues.

dmesg shows some entries about this mass storage and disable it

any hints howto get this device enabled?

**Comment by MaBecker** [comment]
some details from dmesg

```c
[34860.373146] usb 1-1: USB disconnect, device number 6
[34865.565963] usb 1-1: new high-speed USB device number 7 using musb-hdrc
[34865.695874] usb 1-1: New USB device found, idVendor=1db7, idProduct=0220
[34865.695898] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[34865.695909] usb 1-1: Product: Digi-Photo-Frame
[34865.695918] usb 1-1: Manufacturer: Smedia  inc.
[34865.695927] usb 1-1: SerialNumber: 14024689FA08
[34865.700745] usb-storage 1-1:1.0: USB Mass Storage device detected
[34865.718087] scsi host5: usb-storage 1-1:1.0
[34868.482863] scsi 5:0:0:0: Direct-Access     Generic  Storage RamDisc  1.00 PQ: 0 ANSI: 0 CCS
[34868.492937] sd 5:0:0:0: Attached scsi generic sg0 type 0
[34868.493225] sd 5:0:0:0: [sda] 1 512-byte logical blocks: (512 B/512 B)
[34868.494865] sd 5:0:0:0: [sda] Write Protect is off
[34868.494892] sd 5:0:0:0: [sda] Mode Sense: 03 00 00 00
[34868.499156] sd 5:0:0:0: [sda] No Caching mode page found
[34868.504604] sd 5:0:0:0: [sda] Assuming drive cache: write through
[34868.555776] sd 5:0:0:0: [sda] Attached SCSI removable disk
[34868.664729] usb 1-1: USB disconnect, device number 7
```

**Comment by petrkr** [comment]
Do not know what kind of device you have. Beagle bone itself does not disconnect that USB device...

**Comment by atc1441** [comment]
Hey. The problem is that the MZ100 has not the "USB" firmware flashef

**Comment by petrkr** [comment]
> Hey. The problem is that the MZ100 has not the "USB" firmware flashef

I thought that it has samsung's pricetag.

Just for test, what about keeping MZ100 in "reset" ? Like press and hold "forever" reset button, would that help? As long MZ100 will not boot up and not turn off USB on IT8951.

I can try that on another panel at Lab later today. But if he have that near it now, it could be faster to test

**Comment by MaBecker** [comment]
> But if he have that near it now, it could be faster to test

Yes I do ;-)

**Comment by MaBecker** [comment]
> Just for test, what about keeping MZ100 in "reset" ? Like press and hold "forever" reset button, would that help? As long MZ100 will not boot up and not turn off USB on IT8951.

Good point, will try this immediately.

**Comment by MaBecker** [comment]
Test result:

* pressing the button  does not identify the usb device, 
* release the button,  MZ100 takes over 
* usb is switched off

**Comment by petrkr** [comment]
So it means, reset button will be connected to IT8951 aswell probably. 

![image](https://user-images.githubusercontent.com/6428351/99368724-cab83f80-28bb-11eb-85f9-90a2c26f738a.png)

So then reflash that MZ100.
https://github.com/atc1441/88MZ100
you will need 
 - USB Uart
 - solder 3 pins (tx,rx,gnd, check pinout on repo, aswell it's on 4pin header next to that pad array)
 - 88MZ100_Uart_flasher.py
 - firmware itself https://github.com/atc1441/88MZ100/tree/master/PriceTag%206%20inch here
 - 2nd stage from https://github.com/atc1441/88MZ100/tree/master/88MZ100_CustomFirmware

**Comment by MaBecker** [comment]
Thanks, just found it and started reading ;-)

**Comment by MaBecker** [comment]
https://github.com/atc1441/88MZ100/blob/master/PriceTag%206%20inch/Pinout%206%20inch%20pricetag.jpg

**Comment by atc1441** [comment]
Just keep reseting the MZ100 does not help as the pins are floating then. My firmware is just bringing all the pins into a known state nothing special

**Comment by MaBecker** [comment]
Ok, now there is a /dev/sda

```c
[ 7678.786093] usb 1-1: new high-speed USB device number 26 using musb-hdrc
[ 7678.916073] usb 1-1: New USB device found, idVendor=1db7, idProduct=0220
[ 7678.916098] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 7678.916109] usb 1-1: Product: Digi-Photo-Frame
[ 7678.916118] usb 1-1: Manufacturer: Smedia  inc.
[ 7678.916127] usb 1-1: SerialNumber: 14024689FA08
[ 7678.921460] usb-storage 1-1:1.0: USB Mass Storage device detected
[ 7678.940934] scsi host14: usb-storage 1-1:1.0
[ 7679.943641] scsi 14:0:0:0: Direct-Access     Generic  Storage RamDisc  1.00 PQ: 0 ANSI: 0 CCS
[ 7679.952427] sd 14:0:0:0: Attached scsi generic sg0 type 0
[ 7679.957125] sd 14:0:0:0: [sda] 1 512-byte logical blocks: (512 B/512 B)
[ 7679.959106] sd 14:0:0:0: [sda] Write Protect is off
[ 7679.959133] sd 14:0:0:0: [sda] Mode Sense: 03 00 00 00
[ 7679.960368] sd 14:0:0:0: [sda] No Caching mode page found
[ 7679.965931] sd 14:0:0:0: [sda] Assuming drive cache: write through
[ 7680.022491] sd 14:0:0:0: [sda] Attached SCSI removable disk
root@ctl10-99:~# ll /dev/sd*
brw-rw---- 1 root disk 8, 0 Nov 17 11:47 /dev/sda
```

Two hints when running on Linux or Mac OS X

* convert 88MZ100_Uart_flasher.py to unix
* use python3 to run the flasher

**Comment by petrkr** [comment]
Under arch linux without problem.

Python2 is deprecated sice January and should not be used at all. Python3 should be default for 'python' command. 


But suggest add interpretter python3 to scripts could be good idea @atc1441 ?

**Comment by MaBecker** [comment]
@petrkr can you please add a sample file to your repo for testing?

**Comment by atc1441** [comment]
The flasher should allready be useable with python3

I do not use python 2 anymore, only for not compatible stuff like IDA.

@petrkr  What interpreter do you mean? I did not understand.

**Comment by petrkr** [comment]
https://github.com/atc1441/88MZ100/blob/master/88MZ100_Uart_flasher.py#L1

here use `python3` instead `python` or use `/usr/bin/env python3`

because there are still many old systems, which has /usr/bin/python pointed to 2.x version (mostly old raspbians etc).

**Comment by atc1441** [comment]
Ah ok got that.

**Comment by MaBecker** [comment]
Thanks for the examples - works like designed - many thanks.
