### ISSUE TITLE
Have you tried the raw mode update ?

### ISSUE THREAD

**Issue by MaBecker** [petrkr/it8951usb#10]
infos from https://www.waveshare.net/w/upload/1/18/IT8951_D_V0.2.4.3_20170728.pdf

```
Added 0xA5 - Fast Write Memory command for load full image

In this version, we added the following new commands:
Fast write memory command 0xA5 which is for fast load full width image
(continuous pixels data) and it the transfer rate may speed up to Max:
30MB/Secs.

```

I tried the WaveShare Tool to upload images  and it was much faster.

**Comment by petrkr** [comment]
Yes this works for waveshare panels, but this repo was for some OEM panels and it's firmware does not support this function. Also does not supports partial refresh on USB (but must supports on SPI as original MCU on that pricetag is working)

**Comment by MaBecker** [comment]
Thank's for your feedback.

Edit: The WaveShare Tool was tested with one of those OEM from atc1441 on Windows via USB
