### ISSUE TITLE
Is it possible to blank the screen white instead of gray? 

### ISSUE THREAD

**Issue by MaBecker** [petrkr/it8951usb#2]
Using `./it8951 -c -m 0  /dev/sda 0 0 1024 768`to blank the screen and it turns out gray.

What am i missing?

![IMG_0926_small](https://user-images.githubusercontent.com/15932646/99395797-3cef4b00-28e1-11eb-94a8-0ee353e5e99c.jpg)

**Comment by petrkr** [comment]
Yes, it was my test when I tried changes, so I used -c instead image and it stay on gray... Maybe I will do argument for 0-255 value for now I commit white memset

**Comment by MaBecker** [comment]
That was quick - Thanks!

Works perfect.
