### ISSUE TITLE
.bmp to .raw

### ISSUE THREAD

**Issue by MaBecker** [petrkr/it8951usb#4]
Can you please explain which command was used to convert tesline.bmp to testline.raw?

**Comment by petrkr** [comment]
I used `convert` command, but parameters I have to find again as long my bash.history gets corrupt since that

**Comment by petrkr** [comment]
So command is this
`convert octopustest.bmp -depth 8 gray:octopustest.raw`

Maybe it can handle also png or other files. You can try. But important for now is to have exact width of source picture (for this eInk it's `1024`).. I did not make any calculations about dynamic and memory maps etc... anyway it's first working version, so it works only for full-length lines

![20201118_191241](https://user-images.githubusercontent.com/6428351/99570423-32f94500-29d2-11eb-98e2-f08c9cff1a0f.jpg)

**Comment by MaBecker** [comment]
Ups, ok should have taken a detailed look into the code, because I am trying to send a 500x500 image ....

**Comment by petrkr** [comment]
Yes I did not have documented that yet. It is possible to do that, but need to calculate in offsets with that and "skip" sending rest line. But for now I have limitted time for that and trying to understand that Kernel-space

**Comment by MaBecker** [comment]
Yes, a kernel driver would be great to get around sudo ....

**Comment by petrkr** [comment]
Or you can take look at that 
It's here
https://github.com/petrkr/it8951usb/blob/master/main.c#L286-L298

There is important thing, you need to split data by MAX_TRANSER size as it's SCSI max size per packet.

also that memory is mapped "in row", so 2nd line is 1024, 3rd line is 2048 offset etc...

so if you need to that 500x500 you need to write to mempry
0 - 500
1024 - 1524
2048 - 2548

etc... All need to be splitted by 60kB chunks so on this it will be actually slow, as it will send only 500b chunks for every line

**Comment by MaBecker** [comment]
sending a full screen is total fine, as this EDP is very fast

**Comment by petrkr** [comment]
> Yes, a kernel driver would be great to get around sudo ....

to get around sudo you just need to put user to group 'disk'
```
ls /dev/sg0 -lh
crw-rw---- 1 root disk 21, 0 Nov 18 19:03 /dev/sg0
```

then you do not need sudo and it should be like that, you should never use sudo if it is really not necessary (like system updates, or edit system files)

**Comment by MaBecker** [comment]
just can confirm that this works on my side - thanks for your support 

```c
convert image-1024x390.jpg -background white -depth 8 gray:image-1024x390.raw
./it8951 /dev/sda -m 4 0 200 1024 390 < image-1024x390.raw
```

**Comment by petrkr** [comment]
> just can confirm that this works on my side - thanks for your support
> 
> ```c
> convert image-1024x390.jpg -background white -depth 8 gray:image-1024x390.raw
> ./it8951 /dev/sda -m 4 0 200 1024 390 < image-1024x390.raw
> ```

And if you do not want generate that .raw file, you can use PIPE and stdout

so command will be 

```
convert image-1024x390.jpg -background white -depth 8 gray:- | ./it8951 /dev/sda -m 4 0 200 1024 390
```

**Comment by MaBecker** [comment]
just started `sudo apt-get install imagemagick` to have both tools on the same box ;-)

**Comment by MaBecker** [comment]
```c
convert -background white -fill black  \
-font Ubuntu -pointsize 400 label:"42"   -gravity Center -extent 1024x758   \
-depth 8 gray:   | ./it8951 /dev/sda 0 0 1024 758
```
![IMG_0939_small](https://user-images.githubusercontent.com/15932646/99578396-11518b00-29dd-11eb-9a3e-b1d53433388b.jpg)

**Comment by MaBecker** [comment]
convert -background white -fill black   -font Ubuntu -pointsize 400 label:"42"   -gravity Center -extent 1024x758   -depth 8 gray:   | ./it8951 /dev/sda 0 0 1024 758

![IMG_0940](https://user-images.githubusercontent.com/15932646/99578719-84f39800-29dd-11eb-8b84-8c99e07a7bc7.JPG)

**Comment by MaBecker** [comment]
> Or you can take look at that
> It's here
> https://github.com/petrkr/it8951usb/blob/master/main.c#L286-L298
> 
> There is important thing, you need to split data by MAX_TRANSER size as it's SCSI max size per packet.
> 
> also that memory is mapped "in row", so 2nd line is 1024, 3rd line is 2048 offset etc...
> 
> so if you need to that 500x500 you need to write to mempry
> 0 - 500
> 1024 - 1524
> 2048 - 2548
> 
> etc... All need to be splitted by 60kB chunks so on this it will be actually slow, as it will send only 500b chunks for every line

what about this implementation?

https://github.com/Seagate/it8951

**Comment by petrkr** [comment]
It looks line.. :) Of course I can not compete with full-time paid developers from Seagate company.

**Comment by MaBecker** [comment]
Don't worry, I realy like your tool!

**Comment by petrkr** [comment]
I test their library and also they do not have solved smaller image than width of display:

Two test case
first is 200x200px picture
second is 1024x200 picture (same but only made cavas width 1024)

also fast write does not work (same as at this one) and load image also does not work (same as this one)..  also display only part of screen does not work It's probably because FW of that pricetag does not support those SCSI commands probably.

Would be good to get some other firmware to get those commands to work. But I am afraid we can not get any.. Atlest I was able to read SPI flash by theirs tool, but how to decompile? Or where to get SDK to compile new ? Maybe open issue on Seagate's github? Because they mention some firmware there, but it's not part of repository

```
[petrkr@pkdell it8951 (master %=)]$ sudo ./it8951_cmd -v /dev/sg0 write Untitled.pgm display
[INFO] Opening ITE device: /dev/sg0
[INFO] sg: get system info
[INFO] image: loading from file Untitled.pgm
[INFO] image: found PGM header - x=200 y=200 maxcolor=255
[INFO] sg: write to memory @0x00195870 (40000 bytes, fast=0)
[INFO] sg: display area
[INFO] Zone (user args): x=0 y=0 width=0 height=0
[INFO] Zone (sanitized): x=0 y=0 width=1024 height=758


[petrkr@pkdell it8951 (master %=)]$ sudo ./it8951_cmd -v /dev/sg0 write Untitled.pgm display
[INFO] Opening ITE device: /dev/sg0
[INFO] sg: get system info
[INFO] image: loading from file Untitled.pgm
[INFO] image: found PGM header - x=1024 y=200 maxcolor=255
[INFO] sg: write to memory @0x00195870 (204800 bytes, fast=0)
[INFO] sg: display area
[INFO] Zone (user args): x=0 y=0 width=0 height=0
[INFO] Zone (sanitized): x=0 y=0 width=1024 height=758
```

![20201119_191044](https://user-images.githubusercontent.com/6428351/99706331-31e01a80-2a9b-11eb-91ec-6188f725f46d.jpg)
![20201119_191051](https://user-images.githubusercontent.com/6428351/99706351-373d6500-2a9b-11eb-815d-40a350a0dc19.jpg)

**Comment by MaBecker** [comment]
Many thanks for testing.

**Comment by MaBecker** [comment]
How did you create the .pgm files?

**Comment by petrkr** [comment]
> How did you create the .pgm files?

just exported them from GIMP. FIle --> Export and instead suffix "bmp" I wrote "pgm". It has export support for it, I used RAW format

**Comment by MaBecker** [comment]
> > Yes, a kernel driver would be great to get around sudo ....
> 
> to get around sudo you just need to put user to group 'disk'
> 
> ```
> ls /dev/sg0 -lh
> crw-rw---- 1 root disk 21, 0 Nov 18 19:03 /dev/sg0
> ```
> 
> then you do not need sudo and it should be like that, you should never use sudo if it is really not necessary (like system updates, or edit system files)

Hi this does not work for me, but this does when executing this command as root ;-)

```bash
echo "myuser  ALL=(ALL) NOPASSWD:/usr/local/bin/it8951" |  tee /etc/sudoers.d/myuser
```
